import {
  Product,
  Supplier,
  Hospital,
  SupplyOrder,
  SupplyOrderItem,
  InventoryItem,
  BankAccount,
  Tender,
  PurchaseOrder,
  POItem,
  SalesOrder,
  SalesItem,
  DeliveryChallan,
  DCItem,
  DailyExpense,
  ExpenseItem,
  SalaryVoucher,
  Allowance,
  Deduction,
  SalesTaxInvoice,
  InvoiceItem,
} from '../client/hooks/useStore';

const generateId = () => Math.random().toString(36).substring(2, 11);

export const mockProducts: Product[] = [
  {
    id: generateId(),
    genericName: 'Diclofenac sodium',
    brandName: 'MOTIV',
    manufacturer: 'Biogen Pharma',
    strength: '50mg',
    unit: 'Tab',
    packSize: 20,
    gstRate: 0,
    minimumStock: 100,
    maximumStock: 5000,
    reorderPoint: 500,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    genericName: 'Diclofenac sodium',
    brandName: 'DEFINA',
    manufacturer: 'Pharmedic Labs',
    strength: '50mg',
    unit: 'Cap',
    packSize: 30,
    gstRate: 18,
    minimumStock: 100,
    maximumStock: 5000,
    reorderPoint: 500,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    genericName: 'Granicip Injection',
    brandName: 'Inj Granicip',
    manufacturer: 'GETZ',
    strength: '3ml',
    unit: 'Inj',
    packSize: 1,
    gstRate: 0,
    minimumStock: 50,
    maximumStock: 2000,
    reorderPoint: 200,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    genericName: 'Oxaliplatin',
    brandName: 'Inj Oxaliplatin',
    manufacturer: 'GETZ',
    strength: '100mg',
    unit: 'Inj',
    packSize: 1,
    gstRate: 0,
    minimumStock: 10,
    maximumStock: 500,
    reorderPoint: 50,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    genericName: 'Nexum',
    brandName: 'CAP NEXUM',
    manufacturer: 'GETZ',
    strength: '40mg',
    unit: 'Cap',
    packSize: 30,
    gstRate: 0,
    minimumStock: 100,
    maximumStock: 10000,
    reorderPoint: 1000,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    genericName: 'Getryl',
    brandName: 'TAB GETRYL',
    manufacturer: 'GETZ',
    strength: '1mg',
    unit: 'Tab',
    packSize: 10,
    gstRate: 0,
    minimumStock: 500,
    maximumStock: 50000,
    reorderPoint: 5000,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    genericName: 'Glinext MR',
    brandName: 'TAB GLINEXT MR',
    manufacturer: 'Pharma Co',
    strength: '30mg',
    unit: 'Tab',
    packSize: 30,
    gstRate: 0,
    minimumStock: 100,
    maximumStock: 5000,
    reorderPoint: 500,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
];

export const mockSuppliers: Supplier[] = [
  {
    id: generateId(),
    name: 'Next Pharma Pvt Ltd',
    email: 'info@nextpharma.com',
    phone: '+92-300-1234567',
    address: 'Lahore',
    city: 'Lahore',
    country: 'Pakistan',
    postalCode: '54000',
    licenseNo: 'LIC-001',
    paymentTerms: 'Net30',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    name: 'AJ Mirza',
    email: 'aj@mirza.com',
    phone: '+92-300-1234567',
    address: 'Karachi',
    city: 'Karachi',
    country: 'Pakistan',
    postalCode: '75000',
    licenseNo: 'LIC-002',
    paymentTerms: 'Net15',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    name: 'Getz Pharma',
    email: 'sales@getzpharma.com',
    phone: '+92-300-1234567',
    address: 'Islamabad',
    city: 'Islamabad',
    country: 'Pakistan',
    postalCode: '44000',
    licenseNo: 'LIC-003',
    paymentTerms: 'Net60',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
];

export const mockHospitals: Hospital[] = [
  {
    id: generateId(),
    name: 'Ginum Hospital Gujranwala',
    email: 'info@ginum.com',
    phone: '+92-300-1234567',
    address: 'Gujranwala',
    city: 'Gujranwala',
    country: 'Pakistan',
    postalCode: '50700',
    licenseNo: 'HOSP-001',
    contactPerson: 'Dr. Ahmed',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    name: 'ARMED FORCES INSTITUTE OF CARDIOLOGY',
    email: 'afic@afipk.com',
    phone: '+92-51-9211111',
    address: 'RAWALPINDI CANTT',
    city: 'Rawalpindi',
    country: 'Pakistan',
    postalCode: '46000',
    licenseNo: 'HOSP-002',
    contactPerson: 'Dr. Farooq',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    name: 'FCTH Peshawar',
    email: 'fcth@peshawar.com',
    phone: '+92-91-9216666',
    address: 'Peshawar',
    city: 'Peshawar',
    country: 'Pakistan',
    postalCode: '25000',
    licenseNo: 'HOSP-003',
    contactPerson: 'Dr. Khalid',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
];

export const mockSupplyOrders: SupplyOrder[] = [
  {
    id: generateId(),
    orderNo: '250716-7443',
    hospitalId: mockHospitals[0].id,
    hospitalName: 'Ginum Hospital Gujranwala',
    orderDate: '2025-07-04',
    deliveryDate: '2025-07-20',
    items: [
      {
        id: generateId(),
        productId: mockProducts[2].id,
        productName: 'Inj Granicip 3ml',
        quantity: 400,
        unitPrice: 350,
        amount: 140000,
      },
      {
        id: generateId(),
        productId: mockProducts[3].id,
        productName: 'Inj Oxaliplatin 100mg',
        quantity: 10,
        unitPrice: 6000,
        amount: 60000,
      },
    ],
    totalAmount: 200000,
    status: 'Confirmed',
    createdAt: new Date().toISOString(),
  },
];

export const mockInventoryItems: InventoryItem[] = [
  {
    id: generateId(),
    productId: mockProducts[0].id,
    productName: 'MOTIV 50mg',
    currentStock: 5000,
    reservedStock: 1000,
    availableStock: 4000,
    lastRestockDate: '2025-06-15',
    lastRestockQuantity: 5000,
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    productId: mockProducts[4].id,
    productName: 'CAP NEXUM 40mg',
    currentStock: 900000,
    reservedStock: 0,
    availableStock: 900000,
    lastRestockDate: '2025-09-03',
    lastRestockQuantity: 900000,
    createdAt: new Date().toISOString(),
  },
];

export const mockBankAccounts: BankAccount[] = [
  {
    id: generateId(),
    accountName: 'Allied Bank Limited',
    accountNo: '0649-0010103479530014',
    bankName: 'Allied Bank Limited',
    balance: 500000,
    accountType: 'Checking',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
];

export const mockTenders: Tender[] = [
  {
    id: generateId(),
    pvmsNo: '1004',
    type: 'Tab',
    genericName: 'Diclofenac sodium 50 mg tab',
    brandName: 'MOTIV 50MG TAB',
    manufacturerBrand: 'Biogen Pharma',
    quotationSubmittedBy: 'Ideal Distributor',
    isAuthorizedDistributor: true,
    packSize: "20's",
    retailPrice: 6.05,
    tradePrice: 5.15,
    offerPrice: 2.93,
    gstApplicable: false,
    discountOffered: 52,
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    pvmsNo: '1004',
    type: 'Tab',
    genericName: 'Diclofenac sodium 50mg',
    brandName: 'DEFINA 50MG CAP',
    manufacturerBrand: 'Pharmedic Labs',
    quotationSubmittedBy: 'Ideal Distributor',
    isAuthorizedDistributor: true,
    packSize: "30's",
    retailPrice: 17.8,
    tradePrice: 15.13,
    offerPrice: 3.0,
    gstApplicable: false,
    discountOffered: 83,
    createdAt: new Date().toISOString(),
  },
];

export const mockPurchaseOrders: PurchaseOrder[] = [
  {
    id: generateId(),
    refNo: 'DD/24-25/3890',
    supplierName: 'Next Pharma Pvt Ltd',
    poDate: '2025-06-03',
    deliveryAddress: 'E-64, Block-E Near Jamia Masjid Aqsa Satellite Town, Rawalpindi',
    items: [
      {
        id: generateId(),
        nomenclature: 'TAB GLINEXT MR 30MG(30s)',
        unit: 'Pack',
        quantity: 500,
        rate: 224.32,
        amount: 112160,
      },
      {
        id: generateId(),
        nomenclature: 'TAB GLINEXT MR 60MG(30s)',
        unit: 'Pack',
        quantity: 500,
        rate: 292.66,
        amount: 146330,
      },
    ],
    totalAmount: 258490,
    distributorDiscount: 31018.8,
    netPayableAmount: 227471.2,
    paymentMethod: 'Bank',
    notes: 'Please dispatch stock within 7 days. Supply time must be within 7 days.',
    createdAt: new Date().toISOString(),
  },
];

export const mockSalesOrders: SalesOrder[] = [
  {
    id: generateId(),
    orderId: '3068',
    hospitalName: 'Ginum Hospital Gujranwala',
    orderDate: '2025-07-04',
    receivedDate: new Date().toISOString(),
    items: [
      {
        id: generateId(),
        itemName: 'Inj Granicip',
        strength: '3ml',
        quantity: 400,
        packSize: '1',
        quantityInPacks: 400,
        poRate: 350,
        saleTotal: 140000,
        purchaseRate: 310,
        purchaseTotal: 124000,
      },
      {
        id: generateId(),
        itemName: 'Inj Oxaliplatin',
        strength: '100mg',
        quantity: 10,
        packSize: '1',
        quantityInPacks: 10,
        poRate: 6000,
        saleTotal: 60000,
        purchaseRate: 4500,
        purchaseTotal: 45000,
      },
    ],
    saleTotal: 200000,
    purchaseTotal: 169000,
    profit: 30840,
    paymentStatus: 'Pending',
    createdAt: new Date().toISOString(),
  },
];

export const mockDeliveryChallans: DeliveryChallan[] = [
  {
    id: generateId(),
    dcNo: '240909-5583',
    dcDate: '2024-09-09',
    poNo: 'MS / Ideal Distrs / 04',
    poDate: '2024-09-03',
    buyerName: 'ARMED FORCES INSTITUTE OF CARDIOLOGY',
    address: 'RAWALPINDI CANTT',
    items: [
      {
        id: generateId(),
        product: 'CAP NEXUM 40MG',
        genericName: 'Nexum',
        company: 'GETZ',
        quantity: 900000,
        batch: 'C02084',
        mfgDate: '2024-01-15',
        expiryDate: '2027-01-15',
      },
    ],
    createdAt: new Date().toISOString(),
  },
];

export const mockDailyExpenses: DailyExpense[] = [
  {
    id: generateId(),
    voucherNo: '3688',
    date: '2025-10-10',
    payTo: 'Ibrahim Sb',
    expenses: [
      {
        id: generateId(),
        reference: 'Activity',
        description: 'Paid to Sher Gul CMA Rawalpindi for clearance of Cheques (Getz Pharma)',
        concernPerson: 'Ibrahim Sb',
        amount: 1445150,
        headWiseCategory: 'Activity',
      },
      {
        id: generateId(),
        reference: 'Carriage',
        description: 'Bike Parking-991 Charges PEMH (Usama)',
        concernPerson: 'Ibrahim Sb',
        amount: 20,
        headWiseCategory: 'Carriage',
      },
      {
        id: generateId(),
        reference: 'Kitchen',
        description: 'Nan',
        concernPerson: 'Ibrahim Sb',
        amount: 200,
        headWiseCategory: 'Kitchen',
      },
      {
        id: generateId(),
        reference: 'Kitchen',
        description: 'Olpers Milk 03 Nos',
        concernPerson: 'Ibrahim Sb',
        amount: 267,
        headWiseCategory: 'Kitchen',
      },
      {
        id: generateId(),
        reference: 'Salary',
        description: 'Advance salary Mr. Shahid (Cook)',
        concernPerson: 'Ibrahim Sb',
        amount: 5000,
        headWiseCategory: 'Salary',
      },
    ],
    totalAmount: 1453191,
    attachedReceipts: 17,
    createdAt: new Date().toISOString(),
  },
];

export const mockSalaryVouchers: SalaryVoucher[] = [
  {
    id: generateId(),
    voucherNo: '250926',
    employeeName: 'Mr Shahid',
    date: '2025-09-26',
    grossSalary: 23232,
    allowances: [
      {
        id: generateId(),
        type: 'Daily Allowance',
        amount: 2625,
      },
    ],
    deductions: [
      {
        id: generateId(),
        type: 'Loan Deduction',
        amount: 5000,
      },
      {
        id: generateId(),
        type: 'Advance Salary',
        amount: 11000,
      },
    ],
    netSalaryPayable: 16857,
    bankName: 'Allied Bank Limited',
    accountNo: '0649-0010103479530014',
    createdAt: new Date().toISOString(),
  },
];

export const mockSalesTaxInvoices: SalesTaxInvoice[] = [
  {
    id: generateId(),
    invoiceNo: '03698-24',
    invoiceDate: new Date().toISOString(),
    customerName: 'AFIC-NIHD',
    address: 'RAWALPINDI CANTT',
    orderNumbers: ['230830-5525', '240913-6018', '241003-6153', '241023-6273'],
    orderDates: ['2024-08-30', '2024-08-30', '2024-10-03', '2024-10-23'],
    items: [
      {
        id: generateId(),
        product: 'TAB GETRYL 1MG',
        manufacturerCompany: 'GETZ',
        expiryDate: '2027-12-31',
        quantity: 9000,
        batchNo: 'BATCH-001',
        rate: 2.0,
        gstApplicable: false,
        netRate: 2.0,
        amount: 18000,
      },
      {
        id: generateId(),
        product: 'TAB GETRYL 2MG',
        manufacturerCompany: 'GETZ',
        expiryDate: '2027-12-31',
        quantity: 80000,
        batchNo: 'BATCH-002',
        rate: 1.97,
        gstApplicable: false,
        netRate: 1.97,
        amount: 157600,
      },
      {
        id: generateId(),
        product: 'INJ NEXUM 40MG',
        manufacturerCompany: 'GETZ',
        expiryDate: '2027-12-31',
        quantity: 1500,
        batchNo: 'BATCH-003',
        rate: 150.0,
        gstApplicable: false,
        netRate: 150.0,
        amount: 225000,
      },
    ],
    totalNetAmount: 400600,
    createdAt: new Date().toISOString(),
  },
];
